# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

# Uncomment to apply global transparency to all windows:
# windowrule = opacity 0.89 override 0.89 override, match:class .*

# Disable blur for all xwayland apps
# windowrule = no_blur on, match:xwayland 1

workspace = 1, monitor:DP-3, default:true
workspace = 2, monitor:HDMI-A-1, default:true
workspace = 3, monitor:DP-3, default:true
workspace = 4, monitor:HDMI-A-1, default:true
workspace = 5, monitor:DP-3, default:true
workspace = 6, monitor:HDMI-A-1, default:true
workspace = 7, monitor:DP-3, default:true
workspace = 8, monitor:HDMI-A-1, default:true
workspace = 9, monitor:DP-3, default:true
workspace = 10, monitor:HDMI-A-1, default:true

windowrule = match:class nz.co.mega.megasync, float on
windowrule = match:class nz.co.mega.megasync, move 2155 50
# windowrule = move onscreen cursor -19% 0%, class:nz.co.mega.megasync
windowrule = match:class pot, float on
windowrule = match:class Kodi, workspace 1
# windowrule = float, class:jetbrains-toolbox
# windowrule = match:class jetbrains-toolbox, monitor DP-3
windowrule = match:class jetbrains-toolbox, move 2125 50
# wps
windowrule = match:class ^(wps)$, stay_focused on
